spring.application.name=spring-7-rest-mvc
logging.level.guru.springframework = debug
spring.h2.console.enabled=true

spring.flyway.enabled= false

spring.docker.compose.enabled = false

spring.security.user.name=user1
spring.security.user.password=password

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action= drop-and-create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source= metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target= V1__init-mysql-database.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target= V1__init-mysql-database.sql